### ISSUE TITLE
To open source, to public archive or to move to Alliander internal github org?

### ISSUE THREAD

**Issue by Jonasvdbo** [alliander-opensource/scp-cf-database#1]
Currently `scp-cf-database` is published in Allianders open source github org.

Given that is Allianders open source github org is formost setup for Alliander's open source projects and upstram contributions, I was wondering what the ambitions of this project are.

- Is this project still alive and maintained? If not, can we archive this project?
- If yes, is it the goal to make this a open source project?
- If open source is the goal, who are going to be the maintainers?

Tagging the contributors: @BarryDam @jan-alexander-alliander

**Comment by BarryDam** [comment]
Yes it 's still alive and maintained by me.

I will move it to internal alliander packages any soon

**Comment by Jonasvdbo** [comment]
@BarryDam Perfect. Thanks for the update. 

Btw Do you know this is also the case for scp-cf-database (https://github.com/alliander-opensource/scp-cf-database/issues/1)?
